version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: teslodb
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
